### ISSUE TITLE
Network related packages fail to merge

### ISSUE THREAD

**Issue by hifromash1982** [pimvullers/elementary#165]
wingpanel-indicator-network & switchboard-plug-network & switchboard-plug-onlineaccounts all fail to merge. I get this error while compiling:

error: Package `libnm-glib' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `libnm-util' not found in specified Vala API directories or GObject-Introspection GIR directories

Where can I find these files (or what am I doing wrong)? Other than that I got things working fairly well; the wingpanel-keyboard does not seem to work very well with east-asian languages, but that is not a huge deal. 

Thanks for all the work!

**Comment by pimvullers** [comment]
Should be fixed now (networkmanager from overlay must be used).

**Comment by hifromash1982** [comment]
The wingpanel-indicator-network does emerge now, but the switchboard ones still fail (both the ~amd64 and 9999 versions). I've added some info on the ~amd64 versions. Please let me know if there is any more information you need. 




[switchboard-plug-network.docx](https://github.com/pimvullers/elementary/files/776098/switchboard-plug-network.docx)
[switchboard-plug-onlineaccounts.docx](https://github.com/pimvullers/elementary/files/776097/switchboard-plug-onlineaccounts.docx)

**Comment by spijet** [comment]
Didn't work in my case (had the same error as in OP). Trying to re-merge NetworkManager with USE="vala" now, will see if this helps. If it does, maybe it's a good idea to add `net-misc/networkmanager[vala]` to dependencies?
